require_relative '../lib/houston_dog_adoption/version.rb'
require_relative '../lib/houston_dog_adoption/cli.rb'
require_relative '../lib/houston_dog_adoption/dog.rb'
require_relative '../lib/houston_dog_adoption/scraper.rb'
require 'open-uri'
require 'nokogiri'
